apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: robinispig/rust_bin:v0.1.1
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: REDIS_HOST
              value: redis-service
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: REDIS_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: redis-secret
                 key: redis-password
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password